server:
  port: 8080

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/experimental
    username: root
    password: 110120
    name: experimental
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

excellent:
  cancer:
    owner:
      name: XyParaCrim
      organization: Excellent-Cancer
    fastdfs:
      properties: fastdfs.properties
      enabled: false
    jdbc:
      enabled: false
    running:
      enabled: false
      document-repositories: /Users/yanjiaxun/document

logging:
  level:
#    web: DEBUG
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: excellent.cancer.gray.light.jdbc.entities


