server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/experimental
    username: root
    password: 110120
    name: experimental
    driver-class-name: com.mysql.cj.jdbc.Driver

excellent:
  cancer:
    owner:
      name: XyParaCrim
      organization: Excellent-Cancer
    fastdfs:
      properties: fastdfs.properties
      enabled: false
    jdbc:
      enabled: false

logging:
  level:
#    web: DEBUG
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
