server:
  port: 8080

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:6446/experimental?allowMultiQueries=true
#    url: jdbc:log4jdbc:mysql://gz-cynosdbmysql-grp-a06qz6ov.sql.tencentcdb.com:23833/experimental?allowMultiQueries=true
    username: root
#    password: xyparacrim110
    password: 110120
    name: experimental
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

floor:
  repository:
    enabled: true
    details:
      database-location: /Users/yanjiaxun/document
  file:
    storage:
      enabled: true
      details:
        config-location: fastdfs.properties

gray:
  light:
    source:
      enabled: true
    blog:
      enabled: true
    book:
      enabled: true
    owner:
      enabled: true
    document:
      enabled: true
      check-update:
        enabled: true
      upload-pending:
        enabled: true
    note:
      enabled: true
      check-update:
        enabled: true
      upload-pending:
        enabled: true

logging:
  level:
#    web: DEBUG
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: gray.light.*.entity
