server:
  port: 8080

spring:
  redis:
    timeout: 5000
    lettuce:
      pool:
        min-idle: 8
  datasource:
    url: jdbc:mysql://localhost:6446/experimental?allowMultiQueries=true
    #    url: jdbc:log4jdbc:mysql://gz-cynosdbmysql-grp-a06qz6ov.sql.tencentcdb.com:23833/experimental?allowMultiQueries=true
    username: root
    #    password: xyparacrim110
    password: 110120
    name: experimental
  #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  session:
    store-type: redis
  elasticsearch:
    rest:
      uris: http://localhost:9200
  quartz:
    properties:
      "org.quartz.threadPool.threadCount": "2"


floor:
  repository:
    enabled: true
    details:
      database-location: /Users/yanjiaxun/document
  file:
    storage:
      enabled: true
      details:
        config-location: fastdfs.properties

gray:
  light:
    source:
      enabled: true
    blog:
      enabled: true
    book:
      enabled: true
    owner:
      enabled: true
    document:
      enabled: true
      check-update:
        enabled: false
      upload-pending:
        enabled: false
    note:
      enabled: true
      check-update:
        enabled: false
      upload-pending:
        enabled: false

logging:
  level:
    #    web: DEBUG
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
        data:
          elasticsearch:
            client:
              WIRE: TRACE

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: gray.light.*.entity
