server:
  port: 8080

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:6446/experimental
    username: root
    password: 110120
    name: experimental
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

floor:
  repository:
    enabled: false
    details:
      database-location: /Users/yanjiaxun/document
  file:
    storage:
      enabled: false
      details:
        config-location: fastdfs.properties

logging:
  level:
#    web: DEBUG
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: gray.light.owner.entity
